# Generated by Django 6.0.2 on 2026-02-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto')], default='EXPENSE', max_length=10),
        ),
    ]
